Support "-nan" value in Fetch command.
multiplay/go-rrd pull request #14
Opened 2017-09-28 14:13 UTC by remeh

2017-09-28 14:30 UTC, stevenh requested changes
Thanks for the PR @remeh could update the fetch test so one of the values is -nan so we get coverage on this please.
https://github.com/multiplay/go-rrd/blob/master/mockserver_test.go#L33

Also could you update your commit message with the detail I added to your PR description please i.e.

> Fetch can return both nan and -nan so add support for latter which was previously missing.

2017-09-28 14:43 UTC, remeh commented
Okay I'll look at that asap.

2017-11-17 13:06 UTC, stevenh commented
@remeh poke ;-)

2017-11-17 13:31 UTC, remeh commented
Hey, sorry for the delay :)
I've added the detail, I'll adapt the test either this afternoon or in the weekend, without fail.
Would you prefer that I add a new entry at a new timestamp or just changing one of those `nan` you mentioned to `-nan` would be ok to you?

2017-11-17 13:43 UTC, stevenh commented
Just updating so one is -nan would be fine thanks @remeh you'll also need a rebase with the current version as its in conflict atm.

2017-11-17 13:56 UTC, remeh commented
I guess it's OK now (I've also rebased).

2017-11-17 14:11 UTC, stevenh approved these changes

2017-11-17 14:11 UTC, merged

2017-11-17 14:11 UTC, stevenh commented
All merged thanks @remeh 👍